// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvqyrtankxsovkzafzuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2cXlydGFua3hzb3ZremFmenV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzMyNDYsImV4cCI6MjA3MzUwOTI0Nn0.kBDTB-_nrETTAlC18O6u2jhkkIox68a8jduoasgeLP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});